-- Auto-generated by Rakkib Step 4

-- Authentik
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authentik') THEN
        CREATE ROLE authentik WITH LOGIN PASSWORD 'authentik-db-pass';
    ELSE
        ALTER ROLE authentik WITH PASSWORD 'authentik-db-pass';
    END IF;
END
$$;
SELECT 'CREATE DATABASE authentik OWNER authentik' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'authentik') \gexec

-- n8n
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'n8n') THEN
        CREATE ROLE n8n WITH LOGIN PASSWORD 'n8n-db-pass';
    ELSE
        ALTER ROLE n8n WITH PASSWORD 'n8n-db-pass';
    END IF;
END
$$;
SELECT 'CREATE DATABASE n8n_db OWNER n8n' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'n8n_db') \gexec

-- NocoDB
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'nocodb') THEN
        CREATE ROLE nocodb WITH LOGIN PASSWORD 'nocodb-db-pass';
    ELSE
        ALTER ROLE nocodb WITH PASSWORD 'nocodb-db-pass';
    END IF;
END
$$;
SELECT 'CREATE DATABASE nocodb_db OWNER nocodb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'nocodb_db') \gexec
