"""Registry-driven service hooks used by Step 5."""

from __future__ import annotations

import subprocess
from pathlib import Path

from rakkib.docker import capture_container_logs, health_check
from rakkib.render import render_file
from rakkib.steps import selected_service_defs


def homepage_services_yaml(
    state,
    svc: dict,
    repo: Path,
    data_root: Path,
    log_path: Path,
    registry: dict,
) -> None:
    """Generate Homepage services.yaml from registry homepage metadata."""
    del svc, repo, log_path
    config_dir = data_root / "data" / "homepage" / "config"
    config_dir.mkdir(parents=True, exist_ok=True)

    groups: dict[str, list[str]] = {}
    for selected_svc in selected_service_defs(state, registry):
        homepage = selected_svc.get("homepage") or {}
        if not homepage:
            continue

        subdomain = state.get(f"subdomains.{selected_svc['id']}", selected_svc["id"])
        href = f"https://{subdomain}.{state.get('domain', 'localhost')}"
        block = (
            f"    - {homepage['name']}:\n"
            f"        href: {href}\n"
            f"        description: {homepage['description']}\n"
            f"        icon: {homepage['icon']}"
        )
        groups.setdefault(homepage["category"], []).append(block)

    lines = ["# Generated by Rakkib — edit manually or re-run Rakkib to regenerate."]
    for category in sorted(groups):
        lines.append(f"- {category}:")
        lines.extend(groups[category])

    (config_dir / "services.yaml").write_text("\n".join(lines) + "\n")


def authentik_blueprints(
    state,
    svc: dict,
    repo: Path,
    data_root: Path,
    log_path: Path,
    registry: dict,
) -> None:
    """Render any selected service Authentik blueprints."""
    del svc, log_path
    blueprints_dir = data_root / "data" / "authentik" / "blueprints" / "custom"
    blueprints_dir.mkdir(parents=True, exist_ok=True)

    for selected_svc in selected_service_defs(state, registry):
        blueprint = (selected_svc.get("authentik") or {}).get("blueprint")
        if not blueprint:
            continue
        tmpl = repo / blueprint
        if tmpl.exists():
            render_file(tmpl, blueprints_dir / f"{selected_svc['id']}.yaml", state)


def authentik_postgres_preflight(
    state,
    svc: dict,
    repo: Path,
    data_root: Path,
    log_path: Path,
    registry: dict,
) -> None:
    """Fail fast if the shared postgres container doesn't have the authentik DB."""
    del state, svc, repo, data_root, log_path, registry
    result = subprocess.run(
        ["docker", "exec", "postgres", "pg_isready", "-U", "authentik", "-d", "authentik"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "authentik postgres pre-flight failed: the 'authentik' database/role is not ready "
            "in the postgres container. Ensure Step 4 completed successfully.\n"
            f"pg_isready output: {result.stdout.strip() or result.stderr.strip()}"
        )


_AUTHENTIK_HEALTH_TIMEOUT = 360


def authentik_wait_healthy(
    state,
    svc: dict,
    repo: Path,
    data_root: Path,
    log_path: Path,
    registry: dict,
) -> None:
    """Wait for authentik-server to become healthy; capture logs on failure."""
    del state, svc, repo, data_root, registry
    if not health_check("authentik-server", timeout=_AUTHENTIK_HEALTH_TIMEOUT):
        capture_container_logs("authentik-server", log_path)
        capture_container_logs("authentik-worker", log_path)
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Health.Status}}", "authentik-server"],
            capture_output=True,
            text=True,
        )
        last_status = result.stdout.strip() or "unknown"
        raise RuntimeError(
            f"authentik-server health check timed out after {_AUTHENTIK_HEALTH_TIMEOUT}s "
            f"(last status: {last_status}). See {log_path} for container logs."
        )


POST_RENDER_HOOKS = {
    "homepage_services_yaml": homepage_services_yaml,
    "authentik_blueprints": authentik_blueprints,
}

PRE_START_HOOKS = {
    "authentik_postgres_preflight": authentik_postgres_preflight,
}

POST_START_HOOKS = {
    "authentik_wait_healthy": authentik_wait_healthy,
}
