"""Step 4 — PostgreSQL.

Deploy PostgreSQL and create one database/user pair per selected service.
"""

from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path

from rakkib.render import render_file, render_text
from rakkib.secrets import ensure_secrets
from rakkib.state import State
from rakkib.steps import VerificationResult


def _repo_dir() -> Path:
    """Return the package data directory (contains ``templates/``)."""
    return Path(__file__).resolve().parent.parent / "data"


def _parse_env(text: str) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env-style string."""
    result: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, value = line.split("=", 1)
            result[key.strip()] = value.strip()
    return result


def _merge_env(candidate_text: str, existing_path: Path) -> str:
    """Return *candidate_text* with any existing keys from *existing_path* preserved."""
    if not existing_path.exists():
        return candidate_text

    existing = _parse_env(existing_path.read_text())
    lines: list[str] = []
    for line in candidate_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            lines.append(line)
            continue
        if "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in existing:
                lines.append(f"{key}={existing[key]}")
            else:
                lines.append(line)
        else:
            lines.append(line)
    return "\n".join(lines) + "\n"


def _generate_init_sql(state: State) -> str:
    """Generate init-services.sql based on selected services."""
    lines = ["-- Auto-generated by Rakkib Step 4", ""]
    foundation = state.get("foundation_services", []) or []
    selected = state.get("selected_services", []) or []
    secrets = state.get("secrets.values", {}) or {}

    def _add_service(name: str, role: str, password: str, db_name: str | None = None) -> None:
        db = db_name or role
        lines.extend(
            [
                f"-- {name}",
                "DO $$",
                "BEGIN",
                f"    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{role}') THEN",
                f"        CREATE ROLE {role} WITH LOGIN PASSWORD '{password}';",
                "    ELSE",
                f"        ALTER ROLE {role} WITH PASSWORD '{password}';",
                "    END IF;",
                "END",
                "$$;",
                f"SELECT 'CREATE DATABASE {db} OWNER {role}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{db}') \\gexec",
                "",
            ]
        )

    if "nocodb" in foundation:
        _add_service("NocoDB", "nocodb", secrets.get("NOCODB_DB_PASS", ""), "nocodb_db")

    if "authentik" in foundation:
        _add_service("Authentik", "authentik", secrets.get("AUTHENTIK_DB_PASS", ""))

    if "n8n" in selected:
        _add_service("n8n", "n8n", secrets.get("N8N_DB_PASS", ""), "n8n_db")

    return "\n".join(lines)


def _apply_sql(sql: str) -> None:
    """Execute *sql* directly inside the postgres container via psql."""
    result = subprocess.run(
        ["docker", "exec", "-i", "postgres", "psql", "-U", "postgres"],
        input=sql,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"psql failed (rc={result.returncode}):\n{result.stderr.strip()}"
        )


def _wait_for_healthy(container: str = "postgres", timeout: int = 60) -> None:
    """Poll Docker health status until *container* is healthy."""
    for _ in range(timeout):
        result = subprocess.run(
            ["docker", "inspect", "--format", "{{.State.Health.Status}}", container],
            capture_output=True,
            text=True,
        )
        if result.stdout.strip() == "healthy":
            return
        time.sleep(1)
    raise RuntimeError(f"Postgres did not become healthy within {timeout}s")


def run(state: State) -> None:
    data_root = Path(state.get("data_root", "/srv"))
    postgres_dir = data_root / "docker" / "postgres"
    init_dir = postgres_dir / "init-scripts"
    init_dir.mkdir(parents=True, exist_ok=True)

    log_path = data_root / "logs" / "postgres.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Generate missing secrets if configured to do so.
    if state.get("secrets.mode") == "generate":
        ensure_secrets(state)

    repo = _repo_dir()

    # 2. Render .env.example candidate and merge with existing .env.
    env_candidate = render_text(
        (repo / "templates" / "docker" / "postgres" / ".env.example").read_text(),
        state,
    )
    env_path = postgres_dir / ".env"
    merged = _merge_env(env_candidate, env_path)
    env_path.write_text(merged)
    # Ensure restrictive permissions.
    os.chmod(env_path, 0o600)

    # 3. Generate init SQL.
    sql = _generate_init_sql(state)
    sql_path = init_dir / "init-services.sql"
    sql_path.write_text(sql)

    # 4. Render docker-compose.yml.
    render_file(
        repo / "templates" / "docker" / "postgres" / "docker-compose.yml.tmpl",
        postgres_dir / "docker-compose.yml",
        state,
    )

    # 5. Start PostgreSQL.
    up = subprocess.run(
        ["docker", "compose", "up", "-d"],
        cwd=str(postgres_dir),
        capture_output=True,
        text=True,
    )
    if up.returncode != 0:
        raise RuntimeError(f"docker compose up failed: {up.stderr.strip()}")

    # 6. Wait for healthy.
    _wait_for_healthy()

    # 7. Apply roles/databases directly so passwords are always in sync.
    #    (The init-scripts directory is only executed by postgres on first boot;
    #    re-runs would leave stale passwords without this direct apply.)
    _apply_sql(sql)

    log_path.write_text("postgres step completed\n")


def verify(state: State) -> VerificationResult:
    # Container running?
    ps = subprocess.run(
        ["docker", "ps", "--filter", "name=^postgres$", "--format", "{{.Names}}"],
        capture_output=True,
        text=True,
    )
    if "postgres" not in ps.stdout:
        return VerificationResult.failure("postgres", "Postgres container is not running")

    # pg_isready?
    ready = subprocess.run(
        ["docker", "exec", "postgres", "pg_isready", "-U", "postgres"],
        capture_output=True,
        text=True,
    )
    if ready.returncode != 0:
        return VerificationResult.failure("postgres", f"pg_isready failed: {ready.stderr.strip()}")

    return VerificationResult.success("postgres", "Postgres is running and accepting connections")
